### PR TITLE
Vampirika/gold and level changes

### PR DESCRIPTION
**Pull request by vampirika**
- Adjusted gold formula
- Added level formula
- Changed hero creeps to be non heroes.
- Adjusted values of many creeps values to be the right level/strength.

### CODE REVIEW

**Comment by vampirika** [comment]
All creep adjusments below - big number is health, small number is armour:

Murloc plaguebearer 180->200
Gnoll Overseer hp 975 -> 1250 armor 5 -> 4
Ogre Lord 900 -> 1400 4->3
Ogre magi hp 600 -> 1000 1 -> 0
Stonemaul bruiser 1300 -> 1150
Hydra hatchling 350 -> 425
Hydra 575 -> 625
Ancient hydra 1600 -> 1800
Sea elemental 550 -> 625
Bandit lord 1500 -> 1350
Bronze dragon whelp 340 -> 420
Salazarian lizard 1200 -> 1400
Sea giant 1200 -> 800 6->3
Sea giant hunter 725->1000 0->2
Sea giant behemoth 1000-> 1200 0->5
Overlord 775->1175
Greater voidwalker 750->1150
Polar bear 475->625
Giant polar bear 900->1000
Harpy queen 750->825
Overlord arachnathid 940->1200
Poison treant 590 ->650
Broodmother 750->1000
Giant skeleton warrior 380->800 4->3
Ghost 300->500
Wraith 700->1200 (removed possession)
Corrupted treant 240->300
Berserk elemental 4->3
Dark troll berserker 450->800
Dark troll shadow priest 240->400
Heretic 600->1000
Makura deepseer 480->800
Makura pooldweller 210->400
Revenant of the seas 900->1000
Revenant of the tides 375->400
Deeplord revenant 2100->1750
Red drake 1225->1150
Vaelastrasz 1950->1800
Saragosa 1600->1800
Taerar 2000->1800
Ysondre 2000->1800
Murmur 2000->2400 18->11
Spiderling 480 -> 390 2->1
Nerubian spider lord 750->1050
Nerubian seer 600->800 1->0
Nerubian queen 950->1100 3->2
Murgul shadowcaster 380->425
Blue dragon whelp 340 -> 420
Giant frost wolf 550 -> 650
Dire frost wolf 750 -> 850
Timber wolf 550 -> 450
Wendigo 550 -> 650
Ice troll priest 360->400
Dragonspawn warrior 775->850
Dragonspawn apprentice 350->425
Small crystalline golem 540->450
Crystalline golem 900 ->1200

--Heroes--
Vile Priestess Hexx 1500->1150 5->6
Gal'darah 975->1150 10->6
Jin'do 975->1150 10->6
Ukorz Sandscalp 1075->1150 10->6
Occulus (lowered acquistion range) 1500->1800
Murloc sorcerer 1475->1000 0->1
Ramzes 1275->1350

**Comment by vampirika** [comment]
@YakaryBovine

**Comment by YakaryBovine** [comment]
Wow, awesome work with all the manual creep stat adjustments.
I'll review this once we're ready to do the gold-focused version, marking it as draft again for now. I think we might get Madsen to review as well, there's a lot of major stuff here!

Would it be possible for you to do a PR with only the code changes and the manual unit changes, leaving out the application of the migration? The PR is so large that Github is lagging and I can't figure out a way around it. If that's very difficult to do, don't worry about it, will just deal with the lag.

**Comment by YakaryBovine** [comment]
Hey @vampirika, this has been sitting stale for a while now. I think I'd like to just get it merged in then worry about the balance afterwards. If you fix up the merge conflicts I'll approve (I would fix them myself but I can't modify your fork!)

**Review by YakaryBovine — APPROVED** [review]
Looks good! The diff is too large for me to review in detail so hopefully nothing breaks.

**Pull request merged**
