### PR TITLE
Scarlet Crusade Icon(s) Update

### LINKED ISSUE #2885: Icons for Scarlet Crusade buildings
xD just hurts my eyes that there's two different colours going on 

image

### PR DESCRIPTION
**Pull request by Technopig1992**
Refreshed Scarlet Crusade building icons. 

Closes #2885

### CODE REVIEW

**Comment by Technopig1992** [comment]
image


image

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
I appreciate you demonstrating that it works for me, that's awesome! The icon implementation seems flawless.

It looks like the pathing map has changed though - I can walk my units over the mountains. You may need to redo the steps at the readme here like Vamp had to do: https://drive.google.com/drive/folders/1Gxxy3cmftl3hI6T4cjX0aEXpeBiSfi-v

**Comment by Technopig1992** [comment]
Thought I'd spare you the minutes of testing xD  hmm thats odd files still there . Ill readd it to be sure.

**Comment by Technopig1992** [comment]
Pathing map fixed and tested

**Review by YakaryBovine — APPROVED** [review]
Looks awesome

**Pull request merged**
