### PR TITLE
Cleaning up the lumber

### PR DESCRIPTION
**Pull request by SebastianTanoni**
Removing some units that were unused and had lumber changed Compensating some lumber costs in gold

### CODE REVIEW

**Comment by YakaryBovine** [comment]
I think you probably wanted to remove the other Wisp gather ability. This one is in the wrong button position for its hotkey and has the wrong tooltip (should be the same as every other worker):
image

Same with the Return side of it, which even refers to lumber:
image

**Comment by SebastianTanoni** [comment]
The one i removed was the wrong one, the one that only works with entangled gold mines. So i just need to change this buttons position i guess?

**Comment by YakaryBovine** [comment]
Mountain Giant's Nature Vitality applies Scroll of Protection to the caster:
image

**Comment by YakaryBovine** [comment]
> The one i removed was the wrong one, the one that only works with entangled gold mines. So i just need to change this buttons position i guess?

Yup and the tooltips.

**Comment by YakaryBovine** [comment]
Hold on sorry, I posted these on the wrong PR, deleting

**Pull request merged**
