### PR TITLE
Sebas changes for gold patcj

### PR DESCRIPTION
**Pull request by SebastianTanoni**
Grom ult changed to Field of Blood
Removed the Gold from the Long March
Unit max level 20->30
Added 2 t0 demon gates to make the upgrade linear

#2034 #2295 #2534

### CODE REVIEW

**Comment by YakaryBovine** [comment]
Unlinking and re-opening this one because it should be done in `main`: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2663

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Looks good. Three comments on the Demon Gate changes.
image
1. The tooltip indicating that you can only build 1, which is on a few of these, is now pointless. Should get rid of that.
2. 2 of the starting Gates are upgraded to Fel Hound gates, which then branch. So the bug described in the Issue still exists.
3. Some of the Demon Gates require Navigation, while others require Stronghold. I'm assuming that's a bug but it's not related to this issue so I'll make a new ticket.

**Comment by YakaryBovine** [comment]
Just noticed another one: QuestStonemaul still says it gives gold. QuestZulfarrak and QuestJinthaAlor both actually give gold, but that could be a separate consideration.

**Comment by SebastianTanoni** [comment]
> Just noticed another one: QuestStonemaul still says it gives gold. QuestZulfarrak and QuestJinthaAlor both actually give gold, but that could be a separate consideration.

Yeah zandalar shrine quest will still give gold for now! Fixed stonemaul though

**Comment by SebastianTanoni** [comment]
#2362 #2701 #2669

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
The icon fix looks good. Full recap of current recap of issues:
1. #2701 should be fixed in `main`, so I'll re-open that issue.
2. #2034 is still bugged due to there being 2 Fel Hound starting gates.
3. Need to remove the "Can only build 1 gate" tooltip since it no longer matters. This might change depending on how (2) gets solved.
4. QuestStonemaul still indicates that it gives "plunder" in the flavour. Need to remove that too.

**Comment by SebastianTanoni** [comment]
@YakaryBovine the bug no longer exists, there is no limit for the gates anymore, so no bug

**Comment by YakaryBovine** [comment]
> @YakaryBovine the bug no longer exists, there is no limit for the gates anymore, so no bug And the tooltip was removed

The limit in the tooltip still exists on my end, for Felguard and Pit Fiend gates at least: 
image

**Review by YakaryBovine — APPROVED** [review]
Nice, happy with this.

**Pull request merged**
