### PR TITLE
Reduced Zombie tankiness and removed some congestion around Stratholme

### PR DESCRIPTION
**Pull request by vampirika**
Health 750->450
Armour 1->0
Number of zombies in Hearthglen reduced from 4 to 3.

### CODE REVIEW

**Comment by vampirika** [comment]
@YakaryBovine

**Comment by vampirika** [comment]
Addressed this ticket as well: https://github.com/AzerothWarsLR/WarcraftLegacies/issues/2665

**Comment by YakaryBovine** [comment]
* Seems like a lot of file changes for moving one Zombie. Any idea what happened with that?
* This can go into `main` instead of `dev`, right? No feature changes here.

**Comment by vampirika** [comment]
> * Seems like a lot of file changes for moving one Zombie. Any idea what happened with that?
> * This can go into `main` instead of `dev`, right? No feature changes here.

I commented above, I adjusted the scourge buildings and some trees in the scourge bases to stop tp congestion.
Yes can go into main

**Comment by YakaryBovine** [comment]
> > * Seems like a lot of file changes for moving one Zombie. Any idea what happened with that?
> > * This can go into `main` instead of `dev`, right? No feature changes here.
> 
> I commented above, I adjusted the scourge buildings and some trees in the scourge bases to stop tp congestion. Yes can go into main

My bad!

**Pull request merged**
