### PR TITLE
Trading Post Creeps

### PR DESCRIPTION
**Pull request by Technopig1992**
- Added 3 neutral hostile ships to the two northern and most south eastern Trading Posts.
- Added a miniature island with an Improved Attack Tower by the south western most Trading Post

Closes:
#2977

### CODE REVIEW

**Comment by Technopig1992** [comment]
Might be worth Sebas or Dave looking at this one first; I never do terrain stuff, but needed a deterrent for the Kul'Tiras ship which wasn't a mass of ships or the high bounty awarding larger ships.

**Comment by YakaryBovine** [comment]
I'm happy with the implementation here, though it does need to go into `dev` now that it has terrain changes. The last thing we want to do is manage terrain conflicts between `main` and `dev`. You don't need to redo anything, I can help you retarget it later.

@SebastianTanoni does this look good to you?

**Comment by Technopig1992** [comment]
Cool , apologies I started it based of Main and merged into main thinking it was just going to be creeps camps . You sure it's no issue to merge this into Dev being based off main without an annoying amount of conflicts to sort ? I can just as easily re do it.

**Comment by SebastianTanoni** [comment]
image

Green circle is fine, but red circle shouldnt be buildable (or pathable). Rest is fine

**Comment by Technopig1992** [comment]
Conflicts resolved 
Changed base to dev

**Comment by YakaryBovine** [comment]
@Technopig1992 I think you need to push your local branch, doesn't look like this has the regenerated Constants!

**Comment by Technopig1992** [comment]
oops ! my bad , should all be good now.

**Comment by YakaryBovine** [comment]
This PR was still showing diffs that didn't make any sense to me, so I just went ahead and merged the relevant commits into `dev` directly. Not sure what was going on.
So to be clear this PR has been **accepted** and is now in dev, despite me closing the actual PR.

**Comment by Technopig1992** [comment]
No problem , I suspect it has something to do with whatever makes me WE slightly more unit vectors and doodads around whenever  I save and convert back to map data . I try and uncheck them but sometimes it’s hard to differentiate between the actual changes and those 😅. Many thanks ! Sent from my iPhoneOn 3 May 2024, at 23:00, Zakary Boven ***@***.***> wrote:﻿
This PR was still showing diffs that didn't make any sense to me, so I just went ahead and merged the relevant commits into dev directly. Not sure what was going on.
So to be clear this PR has been accepted and is now in dev, despite me closing the actual PR.

**Comment by YakaryBovine** [comment]
> No problem , I suspect it has something to do with whatever makes me WE slightly more unit vectors and doodads around whenever  I save and convert back to map data . I try and uncheck them but sometimes it’s hard to differentiate between the actual changes and those 😅. Many thanks ! Sent from my iPhoneOn 3 May 2024, at 23:00, Zakary Boven ***@***.***> wrote:﻿ This PR was still showing diffs that didn't make any sense to me, so I just went ahead and merged the relevant commits into dev directly. Not sure what was going on. So to be clear this PR has been accepted and is now in dev, despite me closing the actual PR. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Nah honestly I don't think it's anything you did wrong. Just something I'm not understanding about git or GitHub behaviour. When I looked at your list of commits vs. dev it seemed like it should have merged nicely.

**Pull request closed without merging**
