### PR TITLE
Removed all upgrade for flying units, Flight added

### PR DESCRIPTION
**Pull request by SebastianTanoni**
All units that are flying that had an upgrade before now require flight., Flight added to all blacksmith of factions with flying units that had a requirement

### CODE REVIEW

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
This is a non-trivial balance change so it should be targeted at `dev` rather than `main`. I think it should be as simple as clicking the button to change the target branch, but if you run into any issues let me know.

**Comment by YakaryBovine** [comment]
image
Quel'thalas still has this research.

**Comment by YakaryBovine** [comment]
image
Stormwind's Blacksmith doesn't say Flight.

**Comment by YakaryBovine** [comment]
Forgeworks doesn't say Flight.
image

**Comment by YakaryBovine** [comment]
Storm Hammers can't be researched, not sure what's happened here.
image

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Found a handful of surface level issues that need looking at. Note that I only looked at Frostwolf, Stormwind, Quel'thalas, Scourge, and Ironforge. Please look for similar issues for the rest. Need to check
- All air units can still be trained
- All air researches are removed
- All researches related to air units can still be trained
- All Blacksmiths mention Flight in their tooltip

**Comment by SebastianTanoni** [comment]
should be fine, just tested all the factions with flying units

**Review by YakaryBovine — APPROVED** [review]
Looking good I think!

**Pull request merged**
