### PR TITLE
Changing tree line to prevent summons going through

### PR DESCRIPTION
**Pull request by SebastianTanoni**

### CODE REVIEW

**Comment by YakaryBovine** [comment]
@SebastianTanoni I'll have to QA this one in-game. What summoned units did you use to test the thickness?

**Comment by SebastianTanoni** [comment]
> @SebastianTanoni I'll have to QA this one in-game. What summoned units did you use to test the thickness?

I used both the warsong elites and the cenarius summons to test both sides

**Comment by YakaryBovine** [comment]
> > @SebastianTanoni I'll have to QA this one in-game. What summoned units did you use to test the thickness?
> 
> I used both the warsong elites and the cenarius summons to test both sides

Ok sweet. I actually think that sounds pretty thorough and there's nothing in particular I'd want to test beyond that so I'm just going to approve this one.

**Review by YakaryBovine — APPROVED** [review]
LGTM

**Pull request merged**
