### PR TITLE
Black empire Unit and buildings, some upgrades

### PR DESCRIPTION
**Pull request by SebastianTanoni**

### CODE REVIEW

**Comment by YakaryBovine** [comment]
image
Need to remove all references to lumber! So check Black Empire's Town Halls, workers, and Blacksmith.

**Comment by YakaryBovine** [comment]
image
I presume this should be "Unworldly" rather than "Unwordly"?

**Comment by YakaryBovine** [comment]
I think you probably want their damage type to start off as Hero since they're elites:
image

**Comment by YakaryBovine** [comment]
This cheeky tentacle on the left attacked me: 
image

**Comment by YakaryBovine** [comment]
image
Should just be Far Sight!

**Comment by YakaryBovine** [comment]
Should be Obliterate (mechanically identical): 
image

**Comment by SebastianTanoni** [comment]
> image Need to remove all references to lumber! So check Black Empire's Town Halls, workers, and Blacksmith.

Also missing the F building

**Comment by YakaryBovine** [comment]
image
These Obelisk models are funky, it takes like 10 seconds to show anything!

**Comment by YakaryBovine** [comment]
Costs lumber: 
image

**Comment by SebastianTanoni** [comment]
> image These Obelisk models are funky, it takes like 10 seconds to show anything!

https://github.com/AzerothWarsLR/WarcraftLegacies/issues/3007

**Comment by YakaryBovine** [comment]
image
Shouldn't mention destroying trees

**Comment by YakaryBovine** [comment]
image
This guy disappears as soon as I train him

**Comment by YakaryBovine** [comment]
These two buildings have the same hotkey: 
image

**Comment by YakaryBovine** [comment]
The tooltip here is "Research Accelerated Cycle" but the research name is actually Cursed Flesh.
You don't need to do anything here because I'll just automate it, but this is an FYI
image

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Looks great, not much to fix

**Comment by YakaryBovine** [comment]
What's "Old Scroll of Teleportation"? I imagine we need to delete that? Other shops have a different version.
image

**Comment by YakaryBovine** [comment]
Need to move these units to Q and W positions: 
image

**Comment by YakaryBovine** [comment]
Button positions here are all kinds of screwy: 
image

**Comment by YakaryBovine** [comment]
Need to capitalize One here: 
image

**Comment by YakaryBovine** [comment]
Looks like the buff tooltip here got cut off. I imagine you were caught out by the fact that WC3 cuts off tooltips after the first comma!
image

**Comment by YakaryBovine** [comment]
These two buildings have the same icon: 
image

**Comment by YakaryBovine** [comment]
Weird hotkey here: 
image
Might automate hotkeys at some point, but not sure if I should automate hotkey from button position or button position from hotkey...

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Found some more!

**Comment by YakaryBovine** [comment]
Images aren't uploading right now so this is just a comment.
 - Herald's Chaos Siphon says it can raise the caster's mana above its maximum value, but it actually can't. Need to update the tooltip or fix the spell.
 - Remove the first sentence from Chaos Siphon; "transfers Chaotic Energy" implies that Chaotic Energy is a mechanic.
 - I can't figure out how to increase the level of Heal. Need to either add a way to upgrade it or remove the "Level 1" bit from the tooltip.

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Definitely getting into the final touches now!

**Review by YakaryBovine — APPROVED** [review]
OK, looking great!!

**Pull request merged**
