### PR TITLE
Bloodlust Changes

### LINKED ISSUE #2043: Mass Bloodlust and bloodlust stack
- Make sure Mass Bloodlust and Bloodlust share the same buff, and thus do not stack
 - Rename Self-Bloodlust to Frenzy, ensuring it has a custom icon. It should stack with Bloodlust

### PR DESCRIPTION
**Pull request by Technopig1992**
For the horde ability on Kodos changed > Mass bloodlust
Mass Bloodlust Kodos cast range 1000>900
Self Bloodlust ability re-branded >Frenzy
Icons, tooltips etc updated

Closes #2043

### CODE REVIEW

**Comment by YakaryBovine** [comment]
All relevant Fel Horde unit tooltips need updating to say Frenzy: 
image

**Comment by YakaryBovine** [comment]
Fel Horde Barracks should say Frenzy: 
image

**Comment by YakaryBovine** [comment]
This should specify that it applies Bloodlust, and also actually apply Bloodlust: 
image

**Comment by YakaryBovine** [comment]
All Warsong tooltips need to be updated to say Frenzy: 
image

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Good changes, but still needs a lot of work!

**Comment by Technopig1992** [comment]
yeah sorry not even sure how I managed overlook all of those to be honest haha, Have updated and re tested should be fine now.

**Review by YakaryBovine — APPROVED** [review]
Looks awesome, well done.

**Pull request merged**
