### PR TITLE
Bugs

### LINKED ISSUE #2899: Missing Pathing Blockers
image
image

Not sure with the last one as you are able to walk through the gate?
image

### PR DESCRIPTION
**Pull request by Technopig1992**
Magic Sentry removed from SW
Drink the Blood of Mannaroth tooltip updated
Pathing blockers added 

Closes
#2899 
#2934 
#2975

### CODE REVIEW

**Comment by YakaryBovine** [comment]
Need to remove Magic Sentry from this tooltip: 
image

**Comment by YakaryBovine** [comment]
So, this is good, and I don't need you to fix anything, but be careful with quest research tooltips like this:
image

Ultimately the quest itself already has all the information as to what completing it does, the research is just a stepping stone to get there. And if we include the information in both places, we have to keep it up-to-date in both places. That's why for other ones I did something like this:
image

**Comment by YakaryBovine** [comment]
Pathing blockers feel good.

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Couple fixes needed!

**Comment by Technopig1992** [comment]
Ill let you off , turns out blizzard doesn't automate them xD 

With the quest research I could remove the second paragraph and replace with "Required to complete the Blood Pact quest" if you like? I based it off the Plague research originally.

**Review by YakaryBovine — APPROVED** [review]
Nah, I'm happy with this. It's accurate and that's the main concern. Just something amusing to refer back to when it inevitably gets out of sync 🗡️

**Pull request merged**
