### PR TITLE
Tehs changes  | Warsong buildings should be able to cast For the Horde! #2622

### PR DESCRIPTION
**Pull request by Tehia**
Should work as intended #2622
Still new to this, hope that I did not change anything else.

### CODE REVIEW

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
As discussed, we just need to figure out how to get dev merged into your branch so that it doesn't show those extra Glaive changes.
I'm only responding here because it lets me mark the PR as "Changes requested".

**Comment by Tehia** [comment]
Will try to get on it with Madsen today. Because literally I have no idea what happened there.

**Comment by YakaryBovine** [comment]
> Will try to get on it with Madsen today. Because literally I have no idea what happened there.

Oh, I know what happened.
You made your first change from the `Tehs-changes` branch. Then you used the `Tehs-changes` branch again for this one. So your branch has the changes from your first branch, but isn't aware that they've already been pushed. 
The way to avoid this is simple: every time you complete a Pull Request, delete the branch you used for it, then use a new one next time.
In this case, you can solve your current problem by merging `dev` from the main repository into your branch. Madsen might know how to do that in Github Desktop.

**Comment by Ripzss** [comment]
@YakaryBovine Should be fixed now!

**Review by YakaryBovine — APPROVED** [review]
Nice, glad you guys were able to get it fixed. Looks perfect.

**Comment by YakaryBovine** [comment]
@Tehia I recommend deleting `Tehs-changes` at this point. Next time you need to make a change, you can make a new branch off the latest `dev`.

**Pull request merged**
