### PR TITLE
Technopig/BugsDev

### LINKED ISSUE #2647: Revert changes to Warlock's Bloodlust ability
This ability used to be called Windfury, but was renamed to Bloodlust at some point. Bloodlust is the wrong name because Bloodlust gives movement speed and this doesn't.

**Acceptance criteria**
* Rename the ability to Windfury
* Give it a wind-themed icon with Autocast border
* Ensure Warlock Adept Training is updated with the same icon, and its tooltip should reference Windfury
* Warlock's Caster Upgrade tooltip should reference Windfury
* Update the buff to have the same name and icon, and ensure the buff tooltip says what the ability actually does

### LINKED ISSUE #2887: Sentinel ability can't be cast because trees don't exist

### LINKED ISSUE #2895: Fel Horde - Bonebreakers
Remove the 2 pre placed Bonebreakers in BRD as they affect the unit limit.

### PR DESCRIPTION
**Pull request by Technopig1992**
Fel Horde
Removed 4 Bonebreakers from Blackrock Spawn and replaced with 6 Fel Raiders - Closes #2895 
Changed Warlocks Bloodlust ability to Windfury - Closes #2647 
Corrected Caster Upgrade Art for Warlocks 
Corrected Caster Upgrade Art for Chaplains

Sentinels
Changed Sentinel ability to Sentry Ward - Closes #2887

### CODE REVIEW

**Comment by YakaryBovine** [comment]
image
Hotkey should be W according to button position, and need to get rid of that second W in the tooltip.
Pretty cool looking ability!

**Review by YakaryBovine — CHANGES_REQUESTED** [review]
Just one thing to fix I think. I didn't review the Windfury changes because there's no easy way to pick Warsong at the moment, but I'll trust that it's working and revisit the whole faction when we re-add them anyway.

**Comment by vampirika** [comment]
> image Hotkey should be W according to button position, and need to get rid of that second Q in the tooltip. Pretty cool looking ability!

does the image still wanna be the owl sentry one rather than this sentry ward one?

**Comment by YakaryBovine** [comment]
> > image Hotkey should be W according to button position, and need to get rid of that second Q in the tooltip. Pretty cool looking ability!
> 
> does the image still wanna be the owl sentry one rather than this sentry ward one?

Nope, as per https://github.com/AzerothWarsLR/WarcraftLegacies/wiki/Clarity-standards#abilities, the ability must have the Sentry Ward icon because it's mechanically identical to Sentry Ward.

**Comment by Technopig1992** [comment]
There’s always something to slip through ! I’ll amend it and push Ty Sent from my iPhoneOn 20 Apr 2024, at 11:19, Zakary Boven ***@***.***> wrote:﻿


 Hotkey should be W according to button position, and need to get rid of that second Q in the tooltip. Pretty cool looking ability!

does the image still wanna be the owl sentry one rather than this sentry ward one?

Nope, as per https://github.com/AzerothWarsLR/WarcraftLegacies/wiki/Clarity-standards#abilities, the ability must have the Sentry Ward icon because it's mechanically identical to Sentry Ward.

**Comment by Technopig1992** [comment]
> > image Hotkey should be W according to button position, and need to get rid of that second Q in the tooltip. Pretty cool looking ability!
> 
> 
> 
> does the image still wanna be the owl sentry one rather than this sentry ward one?
> 
> 

I see what you mean but also doesn't fit with ability clarity guide lines - however I am thinking if the "extra flavour" you get from the Owl model worth the discrepancy and whether it would be best to just use a normal Sentry Ward.

**Comment by vampirika** [comment]
> > > image Hotkey should be W according to button position, and need to get rid of that second Q in the tooltip. Pretty cool looking ability!
> > 
> > 
> > does the image still wanna be the owl sentry one rather than this sentry ward one?
> 
> I see what you mean but also doesn't fit with ability clarity guide lines - however I am thinking is the "extra flavour" you get from the Owl model worth the discrepancy? and whether it would be best to just use a normal Sentry Ward.

yeah i think if it's functionally the same ability, as that's what the guidelines is, just leave it as is - happy with that and looks good :)

**Comment by Technopig1992** [comment]
> Just one thing to fix I think. I didn't review the Windfury changes because there's no easy way to pick Warsong at the moment, but I'll trust that it's working and revisit the whole faction when we re-add them anyway.

Was supposed to add a note for that. I managed to test Warlocks Caster Upgrade Art and Unit Tooltip via the spawn cheat but was unable to test the rest due to faction being non-existent atm in Dev, ill make a personal note to test it at a later date

**Review by YakaryBovine — DISMISSED** [review]
Looking gooooooood

**Review by YakaryBovine — APPROVED** [review]
double approve

**Pull request merged**
