### PR TITLE
Stratholme & Dalaran

### PR DESCRIPTION
**Pull request by HerrDave**
- Revamped Stratholme
- Revamped Dalaran
- Tyr's Hand now has a Diagonal Gate

- New unit: Diagonal Wooden Gate (Open)
- New unit: Diagonal Wooden Gate (Closed)
- New unit: Diagonal Wooden Gate (Dead)
- New ability: A Close (Diagonal)

- Deleted an unused Doodad

### CODE REVIEW

**Comment by SebastianTanoni** [comment]
Dont approve this yet, not for 3.8

**Comment by YakaryBovine** [comment]
> Dont approve this yet, not for 3.8

Sounds good. Marked it as draft until it's ready to go in.

**Comment by YakaryBovine** [comment]
@SebastianTanoni What version is this going to go in?

**Comment by SebastianTanoni** [comment]
> @SebastianTanoni What version is this going to go in?

4.0

**Pull request merged**
